### ISSUE TITLE
where is Ossian directory?

### ISSUE THREAD

**Issue by X-CCS** [mirfan899/mytts#1]
Hi! Dear author, I have been learning about your project recently, but I did not find this file. Could you please provide it?
+ [the missing document][![MN9KR1.md.png](https://s2.ax1x.com/2019/11/14/MN9KR1.md.png)](https://imgchr.com/i/MN9KR1)

**Comment by mirfan899** [comment]
Clone Ossian `https://github.com/CSTR-Edinburgh/Ossian` and set paths in `ossian.sh`
