### ISSUE TITLE
Did not generate ”.mytts/bin/activate“

### ISSUE THREAD

**Issue by X-CCS** [mirfan899/mytts#2]
Hello! After following the readme steps, I found that this file was not generated. What's the matter?
![cantonese_1](https://user-images.githubusercontent.com/39707537/75365582-5c2fed80-58f8-11ea-9fca-4fb4919b17f5.png)

**Comment by mirfan899** [comment]
You need to create a virtual environment named `.mytts`

**Comment by X-CCS** [comment]
I see. Thank you.
