### ISSUE TITLE
Lack of corpus

### ISSUE THREAD

**Issue by X-CCS** [mirfan899/mytts#4]
Hello, author! Thank you for your project,I have been studying your project recently.
The current situation is that `txt` file can be generated in `./media`, but `wav` file cannot be synthesized. I checked that there is a lack of data corpus, as shown in the following figure:

![YsxfsO.png](https://s1.ax1x.com/2020/05/15/YsxfsO.png)

Can you provide the download address of this data set or the alternative solution?

**Comment by mirfan899** [comment]
Here is the demo for using Ossian http://jrmeyer.github.io/tts/2017/09/15/Ossian-Merlin-demo.html. It's the name of the corpus as an example. You can use any dataset for this purpose.

**Comment by X-CCS** [comment]
Hello, author! The [case](http://jrmeyer.github.io/tts/2017/09/15/Ossian-Merlin-demo.html) you provided only provides the corpus of **romanian**,could you please share your `toy_cn_corpus` so that I can run through this experiment and test the effect? Or is there a simple way to generate cantonese audio files？Thank you！

**Comment by mirfan899** [comment]
Unfortunately, that corpus is proprietary. You need to build your own dataset for Cantonese.

**Comment by X-CCS** [comment]
Thanks you,author. Is there any good construction scheme of cantonese corpus? Public data sets in cantonese are rare.

**Comment by mirfan899** [comment]
For text to speech, you can use any English scheme for Corpus construction.
